### PR TITLE
aruha-262 fix date time validation once and for all

### LINKED ISSUE #274: Prefer Java 8 Time API to Joda Time

### PR DESCRIPTION
**Pull request by rcillo**
Overriding default everit date-time validator by a correct
implementation of RFC3339 validation fixes #274 and another non reported
bug that allowed offset string without colon to be accepted.

### CODE REVIEW

File: src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+    // Valid offsets are either Z or hh:mm. The format hh:mm:ss is not valid
+    private final String dateTimeOffsetPattern = "^.*(Z|((\\+|-)\\d\\d:\\d\\d))$";
+    private final Pattern pattern = Pattern.compile(dateTimeOffsetPattern);
+    private final Optional<String> error = Optional.of(errorMessage);
+
+    @Override
+    public Optional<String> validate(final String dateTime) {
+        try {
+            java.time.LocalDate.parse(dateTime, ISO_OFFSET_DATE_TIME);
```
Comment (jhorstmann) [inline src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java]: Not sure if it makes a difference, but should this be `OffsetDateTime.parse` instead, which has `ISO_OFFSET_DATE_TIME` as the default format.

File: src/test/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidatorTest.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+                "1996-10-45t16:39:57Z", // the RFC requires uppercase T, sorry
+                "1996-10-45T16:39:57z", // the RFC requires uppercase Z as well, sorry again
+                "1996-10-45T16:39:57", // offsets are required
+        };
+
+        final String validDateTimes[] = new String[] {
+                "1996-10-15T16:39:57+07:00", // just a very simple example
+                "1996-10-15T16:39:57-07:00", // just a very simple example
+                "1996-10-15T16:39:57.123+07:00", // simple example with milliseconds
+                "1996-10-15T16:39:57.1234Z", // tricky 4 milliseconds digits (yes it's valid, sorry)
```
Comment (jhorstmann) [inline src/test/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidatorTest.java]: `ISO_OFFSET_DATE_TIME` allows anywhere from 0-9 fractional digits so it might make sense to add tests for all of them.

**Comment by jhorstmann** [comment]
This also fixes the issue with more than 3 digits of fractional seconds, right?

File: src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java [hunk 3]
```diff
@@ -164,58 +163,6 @@ public void requireMetadataOccurredAt() {
     }
 
     @Test
-    public void requireMetadataOccurredAtToBeFormattedAsDateTime() {
```
Comment (AlexanderYastrebov) [inline src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java]: Why this tests were removed?

File: src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+import java.util.regex.Pattern;
+
+import static java.time.format.DateTimeFormatter.ISO_OFFSET_DATE_TIME;
+
+public class RFC3339DateTimeValidator implements FormatValidator {
+
+    private final String errorMessage = "must be a valid date-time";
+
+    // Valid offsets are either Z or hh:mm. The format hh:mm:ss is not valid
+    private final String dateTimeOffsetPattern = "^.*(Z|((\\+|-)\\d\\d:\\d\\d))$";
```
Comment (AlexanderYastrebov) [inline src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java]: One should always remember this:
> Some people, when confronted with a problem, think 
> “I know, I'll use regular expressions.”   Now they have two problems.

The proper way would be to have a look how `ISO_OFFSET_DATE_TIME` is defined and derive proper format based on that:
```java
        DateTimeFormatter rfc3339 = new DateTimeFormatterBuilder()
            .parseCaseInsensitive()
            .append(DateTimeFormatter.ISO_LOCAL_DATE_TIME)
            .appendOffset("+HH:MM", "Z")
            .toFormatter(Locale.getDefault(Locale.Category.FORMAT))
            .withChronology(IsoChronology.INSTANCE)
            .withResolverStyle(ResolverStyle.STRICT);
```

File: src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java (hunk 1 above)
Comment (AlexanderYastrebov) [inline src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java]: No difference from parse POV as result is ignored, but should be changed to avoid confusion

**Comment by AlexanderYastrebov** [comment]
Joda Time should be removed from dependencies

**Comment by AlexanderYastrebov** [comment]
Joda Time should be removed from dependencies

File: src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java (hunk 4 above)
Comment (rcillo) [inline src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java]: @AlexanderYastrebov I tried your suggestion but it accepted seconds in the offset. One of the test cases "1996-10-15T16:39:57+07:00:30" should have been rejected, but it wasn't. Do you have any idea on how to fix this?

File: src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java (hunk 3 above)
Comment (rcillo) [inline src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java]: This tests were all grouped in a more appropriate layer, testing the RFC validator. All test cases were preserved and new ones were added.

File: src/test/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidatorTest.java (hunk 2 above)
Comment (rcillo) [inline src/test/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidatorTest.java]: @jhorstmann done in https://github.com/zalando/nakadi/pull/355/commits/140f61c3741a916ff3de57d13f0c5f57771fda82

File: src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java (hunk 1 above)
Comment (rcillo) [inline src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java]: Done in https://github.com/zalando/nakadi/pull/355/commits/b740c11e371f4ae0bae52f49928e1701880999e7

File: src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java (hunk 4 above)
Comment (AlexanderYastrebov) [inline src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java]: @rcillo 
Yep, unfortunately this solution does not check the format but only ignores seconds.
If your main purpose is to reject second precision offsets then you can do this:
```java
       OffsetDateTime d = OffsetDateTime.parse("1996-10-15T16:39:57+07:00:30", DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        if (d.get(ChronoField.OFFSET_SECONDS) % 60 != 0) {
            throw new IllegalArgumentException("Offset with seconds not supported");
        }
```

Comment (rcillo) [inline src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java]: @AlexanderYastrebov thanks for the tip 👍 

We are mostly interested in validating that the format is RFC 3339 compliant. We need to reject strings that contain seconds in the offset.

**Comment by antban** [comment]
:+1:
