### PR TITLE
ARUHA-110 Enforce lower case enum constants

### LINKED ISSUE #135: EventTypeSchema requires JSON_SCHEMA as schema type
The `EventTypeSchema` spec suggests `json-schema` as valid value for `type`:

```yaml
  EventTypeSchema:
    properties:
      type:
        type: string
        example: 'json-schema'
        description: The type of schema definition (avro, json-schema, etc).
```

However, the application requires `JSON_SCHEMA` as value. Neither `json-schema` nor `json_schema` are accepted.

```sh
$ http -v -a mytok: --verify no https://nakadi-testing.aruha-test.example.org/event-types < event-schema-2.json
POST /event-types HTTP/1.1
Accept: application/json
[...]
User-Agent: HTTPie/0.9.3

{
    "category": "data",
    "name": "order.ORDER_CANCELLED",
    "schema": {
        "schema": "{ \"properties\": { \"order_number\": { \"type\": \"string\" } } }",
        "type": "json_schema"
    }
}

HTTP/1.1 400 Bad Request
[...]
X-Flow-Id: vZW4XYZXO2W3tudzBdi0Jwmy

{
    "detail": "Could not read document: Can not construct instance of de.zalando.aruha.nakadi.domain.EventTypeSchema$Type from String value 'json_schema': value not one of declared Enum instance names: [JSON_SCHEMA]\n at [Source: java.io.PushbackInputStream@27b876fd; line: 5, column: 3] (through reference chain: de.zalando.aruha.nakadi.domain.EventType[\"schema\"]->de.zalando.aruha.nakadi.domain.EventTypeSchema[\"type\"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of de.zalando.aruha.nakadi.domain.EventTypeSchema$Type from String value 'json_schema': value not one of declared Enum instance names: [JSON_SCHEMA]\n at [Source: java.io.PushbackInputStream@27b876fd; line: 5, column: 3] (through reference chain: de.zalando.aruha.nakadi.domain.EventType[\"schema\"]->de.zalando.aruha.nakadi.domain.EventTypeSchema[\"type\"])",
    "status": 400,
    "title": "Bad Request",
    "type": "http://httpstatus.es/400"
}
```

Creation with `JSON_SCHEMA` works perfectly:

```sh
$ http -v -a mytok: --verify no https://nakadi-testing.aruha-test.example.org/event-types < event-schema-2.json
POST /event-types HTTP/1.1
[...]

{
    "category": "data",
    "name": "order.ORDER_CANCELLED",
    "schema": {
        "schema": "{ \"properties\": { \"order_number\": { \"type\": \"string\" } } }",
        "type": "JSON_SCHEMA"
    }
}

HTTP/1.1 201 Created
[...]
X-Flow-Id: p1nSPcqtl7PnmP8XoWAYcOE7
```

### PR DESCRIPTION
**Pull request by tmuehl**
...in the json fields.
And introduced the `EventCategory`.

@v-stepanov @rcillo @jkliff @CyberDem0n @bocytko Please review

Fixes #135

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/137" target="_blank">ReviewNinja

File: src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java [hunk 1]
```diff
@@ -108,7 +109,7 @@ public void whenUpdateExistingEventTypeItUpdates() throws NakadiException, Dupli
 
         repository.saveEventType(eventType);
 
-        eventType.setCategory("new-category");
+        eventType.setCategory(EventCategory.UNDEFINED);
```
Comment (rcillo) [inline src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java]: This test wasn't written in the safest way possible. This change should had broken it. The idea is that updates should indeed be persisted. We should set a different value than the original here.

File: src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java [hunk 2]
```diff
@@ -164,7 +165,7 @@ public void whenTopicCreationFailsRemoveEventTypeFromRepositoryAnd500() throws E
     @Test
     public void whenPUTInvalidEventTypeThen422() throws Exception {
         EventType invalidEventType = buildEventType();
-        invalidEventType.setCategory("");
+        invalidEventType.setCategory(EventCategory.UNDEFINED);
```
Comment (rcillo) [inline src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java]: Is this correct? The test expects a problem with error "may not be empty" for the category field, which you just defined above.

**Comment by rcillo** [comment]
Besides the comments regarding test improvements, it looks good.

**Comment by rcillo** [comment]
@tmuehl github tip https://github.com/blog/1506-closing-issues-via-pull-requests

If you add `Fixes #135` to the description, then, once this PR gets merged, the issue will be automatically solved and linked to this PR :smile:

**Comment by tmuehl** [comment]
@rcillo Thanks, done.

File: src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java (hunk 1 above)
Comment (tmuehl) [inline src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java]: Why should this break the test? The original EventType had the category `UNDEFINED` and the updated one also.

Comment (rcillo) [inline src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java]: I mean, if we are testing updates, than we should change something in order for our assertions have some value. Since we are not changing the original value, then this test is testing nothing.

Comment (tmuehl) [inline src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java]: Ah, I see. You are right.

**Comment by rcillo** [comment]
:shipit:
